###### Shadows #####

shadow = true;
shadow-radius = 14;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.3

##### Fading ##### 

fading = true;
fade-in-step = 0.50;
fade-out-step = 0.50;
fade-out-delta = 4;

##### Transparency / Opacity ##### 

frame-opacity = 1;

##### Corners #####

corner-radius = 10;
round-borders-exclude = [ "class_g     = 'dwm'" ]

##### Blur ###### 

blur-method = "dual_kawase"
blur-size = 12
blur-deviation = true
blur-strength = 7.0

##### General Settings #####

backend = "glx";

dithered-present = true;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

##### Animations #####

animations = (
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.1;
    scale = 0.90;
  },
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.1;
    scale = 0.90;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.10;
  }
);

##### Rules #####

rules: ({

  match = "class_g = 'Rofi'";
	animations = (
	  {
	    triggers = ["close", "hide"];
	    preset = "slide-out";
	    duration = 0.1;
	    direction = "down";
	  },
	  {
	    triggers = ["open", "show"];
	    preset = "slide-in";
	    duration = 0.1;
	    direction = "down";
	  }	
	  );

}

)

